# Generated by Django 6.0.6 on 2026-06-29 20:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم التصنيف')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='أيقونة Font Awesome')),
            ],
            options={
                'verbose_name': 'تصنيف خدمة',
                'verbose_name_plural': 'تصنيفات الخدمات',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم الشركة / المقاول')),
                ('description', models.TextField(verbose_name='وصف الخدمة')),
                ('city', models.CharField(max_length=100, verbose_name='المدينة')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='العنوان')),
                ('phone', models.CharField(max_length=20, verbose_name='رقم الهاتف')),
                ('whatsapp', models.CharField(blank=True, max_length=20, verbose_name='واتساب')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني')),
                ('min_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='أقل سعر')),
                ('max_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='أعلى سعر')),
                ('experience_years', models.PositiveIntegerField(default=0, verbose_name='سنوات الخبرة')),
                ('is_featured', models.BooleanField(default=False, verbose_name='مميز')),
                ('status', models.CharField(choices=[('active', 'نشط'), ('pending', 'قيد المراجعة'), ('inactive', 'غير نشط')], default='pending', max_length=20)),
                ('rating', models.FloatField(default=0.0, verbose_name='التقييم')),
                ('reviews_count', models.PositiveIntegerField(default=0, verbose_name='عدد التقييمات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.servicecategory', verbose_name='التصنيف')),
            ],
            options={
                'verbose_name': 'خدمة',
                'verbose_name_plural': 'خدمات',
                'ordering': ['-is_featured', '-rating', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='services/', verbose_name='صورة')),
                ('is_main', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='services.service')),
            ],
            options={
                'verbose_name': 'صورة خدمة',
                'verbose_name_plural': 'صور الخدمات',
            },
        ),
        migrations.CreateModel(
            name='ServiceReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(default=5)),
                ('comment', models.TextField(verbose_name='التعليق')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='services.service')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'تقييم',
                'verbose_name_plural': 'تقييمات',
                'unique_together': {('service', 'user')},
            },
        ),
    ]
