# Generated by Django 6.0.6 on 2026-06-26 19:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='المدينة')),
            ],
            options={
                'verbose_name': 'مدينة',
                'verbose_name_plural': 'مدن',
            },
        ),
        migrations.CreateModel(
            name='PropertyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نوع العقار')),
            ],
            options={
                'verbose_name': 'نوع العقار',
                'verbose_name_plural': 'أنواع العقارات',
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='الحي')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='properties.city', verbose_name='المدينة')),
            ],
            options={
                'verbose_name': 'حي',
                'verbose_name_plural': 'أحياء',
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان الإعلان')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('listing_type', models.CharField(choices=[('sale', 'للبيع'), ('rent', 'للإيجار')], max_length=10, verbose_name='نوع الإعلان')),
                ('status', models.CharField(choices=[('available', 'متاح'), ('sold', 'تم البيع'), ('rented', 'مؤجر'), ('pending', 'قيد المراجعة')], default='available', max_length=10, verbose_name='الحالة')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='العنوان التفصيلي')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='خط العرض')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='خط الطول')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='السعر')),
                ('area', models.FloatField(verbose_name='المساحة (م²)')),
                ('bedrooms', models.PositiveIntegerField(default=0, verbose_name='غرف النوم')),
                ('bathrooms', models.PositiveIntegerField(default=0, verbose_name='الحمامات')),
                ('floor', models.IntegerField(blank=True, null=True, verbose_name='الدور')),
                ('finishing', models.CharField(blank=True, choices=[('furnished', 'مفروش'), ('semi_furnished', 'نص تشطيب'), ('unfurnished', 'بدون تشطيب'), ('core_shell', 'كور وشيل')], max_length=20, verbose_name='التشطيب')),
                ('has_garage', models.BooleanField(default=False, verbose_name='جراج')),
                ('has_garden', models.BooleanField(default=False, verbose_name='حديقة')),
                ('has_pool', models.BooleanField(default=False, verbose_name='حمام سباحة')),
                ('has_elevator', models.BooleanField(default=False, verbose_name='أسانسير')),
                ('has_security', models.BooleanField(default=False, verbose_name='أمن وحراسة')),
                ('is_featured', models.BooleanField(default=False, verbose_name='إعلان مميز')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='عدد المشاهدات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.city', verbose_name='المدينة')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.district', verbose_name='الحي')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL, verbose_name='المالك')),
                ('property_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.propertytype', verbose_name='نوع العقار')),
            ],
            options={
                'verbose_name': 'عقار',
                'verbose_name_plural': 'عقارات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='properties/', verbose_name='الصورة')),
                ('is_main', models.BooleanField(default=False, verbose_name='صورة رئيسية')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.property', verbose_name='العقار')),
            ],
            options={
                'verbose_name': 'صورة عقار',
                'verbose_name_plural': 'صور العقارات',
            },
        ),
    ]
