# Generated by Django 6.0.6 on 2026-07-01 19:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='avg_rating',
            field=models.FloatField(default=0.0, verbose_name='متوسط التقييم'),
        ),
        migrations.AddField(
            model_name='property',
            name='reviews_count',
            field=models.PositiveIntegerField(default=0, verbose_name='عدد التقييمات'),
        ),
        migrations.CreateModel(
            name='PropertyReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(choices=[(1, '⭐ ضعيف'), (2, '⭐⭐ مقبول'), (3, '⭐⭐⭐ جيد'), (4, '⭐⭐⭐⭐ جيد جداً'), (5, '⭐⭐⭐⭐⭐ ممتاز')], default=5)),
                ('comment', models.TextField(verbose_name='التعليق')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='properties.property')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'تقييم عقار',
                'verbose_name_plural': 'تقييمات العقارات',
                'ordering': ['-created_at'],
                'unique_together': {('property', 'user')},
            },
        ),
    ]
