# Generated by Django 6.0.6 on 2026-09-08 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_property_avg_rating_property_reviews_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='رقم الهاتف'),
        ),
        migrations.AddField(
            model_name='property',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=20, verbose_name='واتساب'),
        ),
    ]
