# Generated by Django 6.0.6 on 2026-09-08 15:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_property_phone_property_whatsapp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإضافة'),
        ),
        migrations.AlterField(
            model_name='property',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=False, verbose_name='إعلان مميز'),
        ),
        migrations.AlterField(
            model_name='property',
            name='listing_type',
            field=models.CharField(choices=[('sale', 'للبيع'), ('rent', 'للإيجار')], db_index=True, max_length=10, verbose_name='نوع الإعلان'),
        ),
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=12, verbose_name='السعر'),
        ),
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('available', 'متاح'), ('sold', 'تم البيع'), ('rented', 'مؤجر'), ('pending', 'قيد المراجعة')], db_index=True, default='available', max_length=10, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='propertyreview',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التقييم'),
        ),
        migrations.AlterField(
            model_name='propertyreview',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='properties.property', verbose_name='العقار'),
        ),
        migrations.AlterField(
            model_name='propertyreview',
            name='rating',
            field=models.PositiveIntegerField(choices=[(1, '⭐ ضعيف'), (2, '⭐⭐ مقبول'), (3, '⭐⭐⭐ جيد'), (4, '⭐⭐⭐⭐ جيد جداً'), (5, '⭐⭐⭐⭐⭐ ممتاز')], default=5, verbose_name='التقييم'),
        ),
        migrations.AlterField(
            model_name='propertyreview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
    ]
