# Generated by Django 6.0.6 on 2026-09-09 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_alter_property_created_at_alter_property_is_featured_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الهاتف'),
        ),
        migrations.AlterField(
            model_name='property',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='واتساب'),
        ),
    ]
